# Generated by Django 5.0.1 on 2024-02-07 16:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_serial', models.CharField(max_length=30)),
                ('dict_date', models.DateField(auto_now_add=True)),
                ('dict_value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='contract_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='apartment',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='overhead',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='premium',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(15000), django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AddField(
            model_name='apartment',
            name='premiumPercentage',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utility',
            name='dict_end_day',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='utility',
            name='dict_start_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='utility',
            name='provider',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.apartment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_amount', models.FloatField(default=0)),
                ('payment_currency', models.CharField(max_length=3)),
                ('payment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rem.owner')),
            ],
        ),
    ]
