# Generated by Django 5.0.1 on 2024-02-13 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0003_due_apartment_check_status_apartment_last_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_day',
            field=models.DateField(default=datetime.datetime(2024, 2, 13, 14, 20, 57, 335501)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2024, 2, 13, 14, 20, 57, 335484)),
        ),
    ]
