# Generated by Django 5.0.1 on 2024-02-14 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0005_remove_contracthistory_apartment_apartment_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='last_check',
            field=models.DateField(default=datetime.date(2024, 2, 14)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_day',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 7, 57, 50, 335968)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 7, 57, 50, 335952)),
        ),
    ]
