# Generated by Django 5.0.1 on 2024-02-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0007_alter_apartment_last_check_alter_todo_end_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkDate', models.DateField(auto_now_add=True)),
                ('cleaning', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('damage', models.BooleanField(default=False)),
                ('animal', models.BooleanField(default=False)),
                ('equipment_damage', models.BooleanField(default=False)),
                ('not_allowed_tenants', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
