# Generated by Django 5.0.1 on 2024-03-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0011_remove_apartment_contract_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='last_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
