# Generated by Django 5.0.1 on 2024-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0012_alter_apartment_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='apartment_history', to='rem.contracthistory'),
        ),
    ]
