# Generated by Django 5.0.1 on 2024-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0013_alter_apartment_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='dues',
            field=models.ManyToManyField(blank=True, related_name='apartment_dues', to='rem.due'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='utilities',
            field=models.ManyToManyField(blank=True, to='rem.utility'),
        ),
    ]
