# Generated by Django 5.0.1 on 2024-03-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0016_bill_paymentbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='rem.paymentbill'),
        ),
    ]
