# Generated by Django 5.0.1 on 2024-03-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0017_bill_payment_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='check_history',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='dues',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='history',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_owner',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='responsible',
        ),
        migrations.AlterField(
            model_name='paymentbill',
            name='amount_text',
            field=models.CharField(max_length=50),
        ),
    ]
