# Generated by Django 5.0.1 on 2024-03-25 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0019_contracthistory_apt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhistory',
            name='apt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Checkhistory_Apartment', to='rem.apartment'),
        ),
        migrations.AddField(
            model_name='todo',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='apt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contracthistory_Apartment', to='rem.apartment'),
        ),
    ]
