# Generated by Django 5.0.1 on 2024-04-03 20:24

import rem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0022_alter_paymentbill_sum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='sent_contract',
            field=models.FileField(blank=True, null=True, upload_to=rem.models.get_doc_path),
        ),
    ]
