# Generated by Django 5.0.1 on 2024-04-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0023_apartment_sent_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='sent_contract',
            field=models.FileField(blank=True, null=True, upload_to='Documents/'),
        ),
    ]
