# Generated by Django 5.0.1 on 2024-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0025_apartment_child_acceptance_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='sent_contract',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
