# Generated by Django 5.0.1 on 2024-04-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0026_alter_apartment_sent_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='type',
        ),
        migrations.RemoveField(
            model_name='utility',
            name='unit',
        ),
    ]
