# Generated by Django 5.0.1 on 2024-04-15 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0027_remove_utility_type_remove_utility_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='utilities',
        ),
        migrations.AddField(
            model_name='utility',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='rem.apartment'),
        ),
    ]
