# Generated by Django 5.0.1 on 2024-04-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0028_remove_apartment_utilities_utility_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='delta',
        ),
        migrations.AlterField(
            model_name='utility',
            name='provider',
            field=models.CharField(default='', max_length=20),
        ),
    ]
