# Generated by Django 5.0.1 on 2024-04-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0029_remove_utility_delta_alter_utility_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='utility_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='utility',
            name='utility_unit',
            field=models.CharField(default='', max_length=5),
        ),
    ]
