# Generated by Django 5.0.1 on 2024-04-22 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0030_utility_utility_type_utility_utility_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='responsible',
        ),
        migrations.AddField(
            model_name='todo',
            name='task_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_responsible_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utility',
            name='util_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='util_responsible_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
